//
// Created by leonardoarcari on 06/06/17.
//

#ifndef ASPECT_PROJECT_SELFTUNEGENERATOR_H
#define ASPECT_PROJECT_SELFTUNEGENERATOR_H

#include "TunerElements.h"
#include <memory>
#include <string>
#include <vector>

namespace ag {

/**
 * GoalTuner is the top-level class for generating AspectC++ code that sets
 * a mARGOt goal value explicitly according to some predicates on a control
 * variable. GoalTuner is the class representing the <goal-tuner> element in
 * XML. Being a generator, it exposes methods to:
 *  - generate code for AspectC++ pointcuts
 *  - generate code for AspectC++ advices
 *  - generate C++ code that advices invoke.
 *  <br>
 *  GoalTuner is move-constructable.
 */
class GoalTuner {
public:
  /**
   * GoalTuner constructor.
   * @param [in] controlVar the ControlVar to predicate on.
   * @param [in] goalName the name of the mARGOt goal to set.
   * @param [in] rules a std::vector of Rule defining the predicates on
   *             \p controlVar
   * @param [in] blockName the mARGOt block name which \p goalName is defined
   *             in.
   */
  GoalTuner(const ControlVar &controlVar, const std::string &goalName,
            std::vector<Rule> &&rules, const std::string &blockName);

  /**
   * GoalTuner move constructor.
   * @param [in] other the GoalTuner object to move into this.
   */
  GoalTuner(GoalTuner &&other);

  /**
   * Generates AspectC++ advices. The advices is executed after the
   * assignment of the control variable (through operator=()). It performs a
   * call to a function generated by GoalTuner::generateHeaders that sets
   * the goal value according to predicates on the new control var value.
   * @param [in] indent a std::string for the indent factor to prepend to each
   *             generated code line.
   * @return a std::vector of AspectC++ advices code.
   */
  std::vector<std::string> generateAdvices(std::string indent);

  /**
   * Generates AspectC++ pointcuts. The pointcuts match the assignment of the
   * control variable through the assignment operator (operator=()).
   * @param [in] indent a std::string for the indent factor to prepend to each
   *             generated code line.
   * @return a std::vector of AspectC++ pointcuts code.
   */
  std::vector<std::string> generatePointcuts(std::string indent);

  /**
   * Generates C++ function definition to set the goal value according to
   * predicates on the control variable value. It's a if-then-else block testing
   * all the conditions described in _rules_ vector passed in the constructor.
   * @param [in] indent a std::string for the indent factor to prepend to each
   *             generated code line.
   * @return a std::string of C++ function definition.
   */
  std::string generateHeaders(std::string indent);

  /**
   * Block name getter.
   * @return the block name.
   */
  const std::string &blockName() const;

private:
  ControlVar _controlVar;
  std::string _goalName;
  std::vector<Rule> _rules;
  std::string _blockName;
};
}

#endif // ASPECT_PROJECT_SELFTUNEGENERATOR_H
